### ISSUE TITLE
Design:  User can authenticate

### ISSUE THREAD

**Issue by JakWai01** [alphahorizonio/consumat.io#20]
See #16 
![image](https://user-images.githubusercontent.com/80920862/115995452-8a33bf00-a5db-11eb-8f65-bf1ed1bc6217.png)
![image](https://user-images.githubusercontent.com/80920862/115995487-c404c580-a5db-11eb-8456-0ec218e46234.png)

**Comment by helmrich** [comment]
@pojntfx Could you provide us with some information on how the authentication flow works? We don't have any experience with OpenID Connect, so do we just need a simple UI with a button or are there other necessary UI elements we should include? Maybe you could also handle the sketch yourself because you're implementing the authentication?

**Comment by pojntfx** [comment]
@helmrich Sure ^^ OIDC w/o the implicit more or less requires a redirect & evaluation of state from query parameters, which I'd argue is also the most architecturally sound solution. In terms of the sketch: I'd recommend sketching authorized/unauthorized pages, if such cases exist. The login/logout flow would basically be a singular button which redirects one to the OIDC AuthN redirect URL.
